import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Login</Link>
        </li>
        <li>
          <Link to="/forgotpassword">ForgotPassword</Link>
        </li>
        <li>
          <Link to="/logindark">Logindark</Link>
        </li>
        <li>
          <Link to="/forgotpassworddark">ForgotPassworddark</Link>
        </li>
        <li>
          <Link to="/users">Users</Link>
        </li>
        <li>
          <Link to="/services">Services</Link>
        </li>
        <li>
          <Link to="/usersalldark">Usersalldark</Link>
        </li>
        <li>
          <Link to="/servicesdark">Servicesdark</Link>
        </li>
        <li>
          <Link to="/editservice">Editservice</Link>
        </li>
        <li>
          <Link to="/editservicedark">Editservicedark</Link>
        </li>
        <li>
          <Link to="/edituser">Edituser</Link>
        </li>
        <li>
          <Link to="/edituserdark">Edituserdark</Link>
        </li>
        <li>
          <Link to="/settingsconfigurations">Settingsconfigurations</Link>
        </li>
        <li>
          <Link to="/settingsconfigurationsone">SettingsconfigurationsOne</Link>
        </li>
        <li>
          <Link to="/settings">Settings</Link>
        </li>
        <li>
          <Link to="/settingsdark">Settingsdark</Link>
        </li>
        <li>
          <Link to="/settingsaccountsettings">Settingsaccountsettings</Link>
        </li>
        <li>
          <Link to="/settingsaccountsettin">Settingsaccountsettin</Link>
        </li>
        <li>
          <Link to="/settingsappearances">Settingsappearances</Link>
        </li>
        <li>
          <Link to="/settingsappearancesdark">Settingsappearancesdark</Link>
        </li>
        <li>
          <Link to="/settingssecurity">Settingssecurity</Link>
        </li>
        <li>
          <Link to="/settingssecuritydark">Settingssecuritydark</Link>
        </li>
        <li>
          <Link to="/settingsappsettings">Settingsappsettings</Link>
        </li>
        <li>
          <Link to="/settingsappsettingsdark">Settingsappsettingsdark</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
